openapi: 3.0.0
info:
  description: This is a stats API
  version: "1.0.0"
  title: Stats API
  contact:
    email: you@your-company.com
paths:
  /get_health_stats:
    get:
      summary: get event stats
      operationId: app.get_health_stats
      description: gets health stats
      responses:
        '200':
          description: Successfully returned a list of car stats
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/HealthStats'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                   type: string
components:
  schemas:
    HealthStats:
      required:
        - storage
        - receiver
        - processing
        - audit
      properties:
        processing:
          type: string
          example: 'a'
        storage:
          type: string
          example: 'a'
        receiver:
          type: string
          example: 'a'
        audit:
          type: string
          example: 'a'
      type: object