openapi: 3.0.0
info:
  description: This is a stats API
  version: "1.0.0"
  title: Stats API
  contact:
    email: you@your-company.com
paths:
  /health: 
    get:
      summary: gets health status
      responses:
        '200':
          description: its alive
  /stats:
    get:
      summary: get event stats
      operationId: app.get_stats
      description: gets return and rent car stats
      responses:
        '200':
          description: Successfully returned a list of car stats
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/ReadingStats'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                   type: string
components:
  schemas:
    ReadingStats:
      required:
        - num_car_returns
        - max_gas_used
        - num_car_rentals
        - max_passenger_limit
      properties:
        num_car_rentals:
          type: integer
          example: 300000
        max_gas_used:
          type: integer
          example: 100
        num_car_returns:
          type: integer
          example: 300000
        max_passenger_limit:
          type: integer
          example: 7
      type: object